name: Deploy GitHub Page

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Publish Frontend project
      run: dotnet publish KrokodyliWeb.Frontend -c Release -o release --nologo
    - name: set repo_info.json
      run: printf '{"UserName"\x3A "%s", "RepoName"\x3A "%s" }\n' ${{ github.repository_owner }} ${{ github.event.repository.name }} > release/wwwroot/repo_info.json
      
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Mark all files as binary
      run:  echo "* binary" > "release/wwwroot/.gitattributes"
      
    - name: Commit wwwroot to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
