name: Run Backend

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 6-23,0 * * 6'
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build backend
      run: dotnet build KrokodyliWeb.Backend -o ./backend_build
    - run: mkdir data_repo
    - name: Run backend 
      run: dotnet ./backend_build/KrokodyliWeb.Backend --data './data_repo/data.json' --mailusername 'USER_PLACEHOLDER' --mailpassword 'PASSWD_PLACEHOLDER'
      
    - name: Commit data_repo to Data branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: data
        FOLDER: ./data_repo
    
